-- Treino Z2 core schema
--
-- Forward-looking, spec-aligned schema (see docs/ARCHITECTURE.md / the
-- original Performance.MD) for a multi-athlete version of this dashboard.
-- Purely additive: it does not touch the existing `strava_activities` /
-- `daily_pmc` tables that the legacy single-athlete dashboard (index.html)
-- reads from.
--
-- NOT APPLIED AUTOMATICALLY. Run this against the Supabase project via the
-- SQL editor or `supabase db push` -- this session has no database
-- execution access (anon key only), so it has not been run or verified
-- against live data.
--
-- Per the spec: the database stores facts only. Derived intelligence
-- (insights, recommendations) is generated by application code, not SQL.

create extension if not exists "pgcrypto";

-- Athlete: physiological profile, one row per auth.users account.
create table if not exists athletes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  birthday date,
  sex text check (sex in ('male', 'female', 'other')),
  height_cm numeric,
  weight_kg numeric,
  ftp integer,
  vo2max numeric,
  max_hr integer,
  resting_hr integer,
  threshold_pace_sec_per_km numeric,
  threshold_power integer,
  preferred_units text not null default 'metric' check (preferred_units in ('metric', 'imperial')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

-- Activity: raw imported activity, immutable once written.
create table if not exists activities (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references athletes(id) on delete cascade,
  provider text not null,
  external_id text,
  name text not null,
  type text,
  start_date timestamptz not null,
  distance_m numeric,
  moving_time_s integer,
  elapsed_time_s integer,
  average_heartrate numeric,
  max_heartrate numeric,
  average_watts numeric,
  weighted_average_watts numeric,
  best_efforts jsonb,
  zone_minutes jsonb,
  raw jsonb,
  created_at timestamptz not null default now(),
  unique (athlete_id, provider, external_id)
);
create index if not exists activities_athlete_date_idx on activities (athlete_id, start_date desc);

-- Workout: scheduled (planned) training, independent of whether it happened.
create table if not exists workouts (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references athletes(id) on delete cascade,
  date date not null,
  kind text not null,
  status text not null default 'planned' check (status in ('planned', 'completed', 'skipped', 'modified', 'cancelled')),
  planned_structure jsonb,
  est_rtss numeric,
  activity_id uuid references activities(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists workouts_athlete_date_idx on workouts (athlete_id, date);

-- Metrics Snapshot: calculated outputs from the Metrics Engine, one per athlete per day.
create table if not exists metrics_snapshots (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references athletes(id) on delete cascade,
  date date not null,
  ctl numeric not null,
  atl numeric not null,
  tsb numeric not null,
  created_at timestamptz not null default now(),
  unique (athlete_id, date)
);
create index if not exists metrics_snapshots_athlete_date_idx on metrics_snapshots (athlete_id, date);

-- Insight: coaching insight generated by the (future) Intelligence Engine.
create table if not exists insights (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references athletes(id) on delete cascade,
  confidence numeric check (confidence >= 0 and confidence <= 1),
  severity text check (severity in ('info', 'warning', 'critical')),
  explanation text not null,
  source_metrics jsonb,
  recommendation text,
  created_at timestamptz not null default now()
);
create index if not exists insights_athlete_created_idx on insights (athlete_id, created_at desc);

-- Row Level Security: each athlete only sees their own data.
alter table athletes enable row level security;
alter table activities enable row level security;
alter table workouts enable row level security;
alter table metrics_snapshots enable row level security;
alter table insights enable row level security;

create policy "Athletes manage their own profile" on athletes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Athletes manage their own activities" on activities
  for all using (athlete_id in (select id from athletes where user_id = auth.uid()))
  with check (athlete_id in (select id from athletes where user_id = auth.uid()));

create policy "Athletes manage their own workouts" on workouts
  for all using (athlete_id in (select id from athletes where user_id = auth.uid()))
  with check (athlete_id in (select id from athletes where user_id = auth.uid()));

create policy "Athletes read their own metrics snapshots" on metrics_snapshots
  for all using (athlete_id in (select id from athletes where user_id = auth.uid()))
  with check (athlete_id in (select id from athletes where user_id = auth.uid()));

create policy "Athletes read their own insights" on insights
  for select using (athlete_id in (select id from athletes where user_id = auth.uid()));
