import { describe, expect, it } from "vitest";
import { calculateCriticalPower } from "../criticalPower";

describe("calculateCriticalPower", () => {
  it("recovers CP and W' exactly from efforts generated by work(t) = 250*t + 20000", () => {
    // Perfect fit by construction: power(t) = 250 + 20000/t.
    const efforts = [
      { durationSec: 60, powerWatts: 250 + 20000 / 60 },
      { durationSec: 300, powerWatts: 250 + 20000 / 300 },
      { durationSec: 1200, powerWatts: 250 + 20000 / 1200 },
    ];

    const result = calculateCriticalPower(efforts);

    expect(result.value).not.toBeNull();
    expect(result.value!.criticalPowerWatts).toBeCloseTo(250, 6);
    expect(result.value!.anaerobicWorkCapacityJ).toBeCloseTo(20000, 3);
    expect(result.value!.rSquared).toBeCloseTo(1, 6);
    expect(result.dataQuality).toBe("high");
    expect(result.confidence).toBeCloseTo(1, 6);
  });

  it("is unavailable with fewer than 2 distinct durations", () => {
    const result = calculateCriticalPower([
      { durationSec: 300, powerWatts: 300 },
      { durationSec: 300, powerWatts: 310 },
    ]);
    expect(result.value).toBeNull();
    expect(result.missingInputs).toContain("fewer than 2 efforts at distinct durations");
  });

  it("is unavailable with zero or one effort", () => {
    expect(calculateCriticalPower([]).value).toBeNull();
    expect(calculateCriticalPower([{ durationSec: 300, powerWatts: 300 }]).value).toBeNull();
  });

  it("flags medium data quality with only 2 efforts, even on a perfect fit", () => {
    const efforts = [
      { durationSec: 60, powerWatts: 250 + 20000 / 60 },
      { durationSec: 1200, powerWatts: 250 + 20000 / 1200 },
    ];
    const result = calculateCriticalPower(efforts);
    expect(result.dataQuality).toBe("medium");
    expect(result.missingInputs).toContain("a third effort at a different duration would improve regression reliability");
  });
});
